### ISSUE TITLE
Multiple interrupts / interrupts reassignment suggested change

### ISSUE THREAD

**Issue by Alex079** [kscheff/BlueBasic#12]
https://github.com/kscheff/BlueBasic/blob/abe8ea6d4b145bbd8c0e2428546ec6f1d8c9b9ba/BLE-CC254x-1.4.2.2/Projects/ble/BlueBasic/Source/BlueBasic_Interpreter.c#L2751-L2775

One might expect that the PICTL state is preserved when a single interrupt is assigned.
Could you please consider changing the "(PICTL & 0x..)" to "(PICTL & ~0x..)"?
Thank you!

**Comment by kscheff** [comment]
I have not used these interrupts, so I am unaware if this part of the code works or has any side effects by changing it.

Edit: looking in the data sheet, you are right this seems to be an obvious bug here. Right now the current development branch is ring-file, the master is quite outdated.

**Comment by kscheff** [comment]
should be fixed in f9d6f804782c11f981773e41d8f94dc315611358

**Comment by Alex079** [comment]
Thank you!
May I ask you to update the BlueBasic-CC2541.bin and BlueBasic-CC2541.hex please?

**Comment by kscheff** [comment]
Sorry, currently in the ring-file tree this configuration doesn't compile.... there are some definitions, libraries etc. not up to date since I moved to the BLE 1.4.2.2 stack. I have no other platform alive for testing these generic builds.

**Comment by Alex079** [comment]
OK. If at some point it would become possible to build recent or backported CC2541 configuration, I would be glad to test the build. I have a couple of HM-10 modules at my disposal.
Thank you for your effort.

**Comment by fanoush** [comment]
HI Alex079 I have rebuild previous version of kscheff's code in CC2541 configuration and used it with JDY-08 module. There were indeed few config changes needed for it to compile and I fixed it somehow. I will check what was needed.
