### ISSUE TITLE
How to program?

### ISSUE THREAD

**Issue by milkpirate** [kscheff/BlueBasic#14]
Hey, I am having trouble getting my CC2541 modules recognized by the TI SmartRF programmer. I read [here](https://github.com/aanon4/BlueBasic/issues/18) that there might be the possibility to program the devices via UART. They suggested my to ask here again, so I do now.

Also if you could tell me (and in the best case also add that to the READEM) how to program these devices the usual/your way? I have the following [CC debugger knock off](https://www.aliexpress.com/item/32988186450.html?af=485352&utm_campaign=485352&aff_platform=portals-tool&utm_medium=cpa&afref=https%3A%2F%2Ftrade.aliexpress.com%2F&dp=d27049e72db7a8a247a223c0cdb6b4cd&spm=a2g0s.9042311.0.0.27424c4d4ZNGtB&cv=47843&mall_affr=pr3&sk=_ePNSNV&aff_trace_key=2334175585934ae6b9d01b18563de083-1606083110341-08270-_ePNSNV&terminal_id=fb63c1f396714d71a5826e52d31a6b12&utm_source=admitad&utm_content=47843) which worked quite well while following the manual [here](https://www.zigbee2mqtt.io/information/flashing_the_cc2531.html) for a zigbee2mqtt bridge.

Thanks for your help in advance!

**Comment by milkpirate** [comment]
Ok, everything worked out in the end. I ordered a the [break out board](https://oshpark.com/shared_projects?utf8=%E2%9C%93&search%5Bquery%5D=bluebasic&button=&search%5Bfilters%5D%5Bpcb_layers%5D%5Btwo_layer%5D=1&search%5Bfilters%5D%5Bpcb_layers%5D%5Bfour_layer%5D=1&records_date_sort=desc&records_per_page=20) and the module got recognised by CC programmer.

**Comment by 0xFACE** [comment]
Another cheap break out board for the HM module: https://pl.aliexpress.com/item/32560353742.html
