### ISSUE TITLE
Interface docu / code?

### ISSUE THREAD

**Issue by milkpirate** [kscheff/BlueBasic#16]
Hey,

I now do have a (kinda) working access to the REPL, so I can start programming. My problem is, that most examples are a little bit too brief for me (f.g. [spi example](https://github.com/kscheff/BlueBasic/blob/master/Examples/spi_mb85rs64v.bbasic#L8) what are the parameters? what does 0, 1 and 3 stand for?).

Could you direct me to some docu (I checked the aanon4's wiki but without luck)? Or could you send me the link to the source where the interpreter handles these lines?

Further, which Basic dialect is BlueBasic based on?

Thank you very much!

**Comment by kscheff** [comment]
The best and most up to date documentation is the source code itself. Mostly you'll find all the explanations in the interpreter code. For the SPI command its here:
https://github.com/kscheff/BlueBasic/blob/185773b8b21ac48e47d44ff3ae42f2bd36ca6b92/BLE-CC254x-1.5.0.16/Projects/ble/BlueBasic/Source/BlueBasic_Interpreter.c#L4300

```
//
// SPI MASTER <port 0|1|2|3>, <mode 0|1|2|3>, LSB|MSB <speed> [, wordsize]
//  or
// SPI TRANSFER Px(y) <array>
//

```

**Comment by milkpirate** [comment]
Ok, great! So in the example port 3 is used, which one is it? P0, P1, P2? Does the numberings map to each other in some sensable way?
![image](https://user-images.githubusercontent.com/9251021/111082402-5bb8c380-8508-11eb-80db-b25a44a75839.png)

Or even more precise, to which `Px_y` does `C SS MO MI` map to?
![image](https://user-images.githubusercontent.com/9251021/111082431-81de6380-8508-11eb-9577-cb78b2a4d9f4.png)

I am sorry for bothering you with all my silly question, but you must just be the most experienced and most responsive person to ask.

**Comment by kscheff** [comment]
reading the source code reveals:

port 0: USART 0, Alt 1
port 1: USART 0, Alt 2
port 2: USART 1, Alt 1
port 3: USART 1, Alt 2

I have not used the SPI interface with BlueBasic, so be prepared to go through some debugging...
The ```SPI``` interface is not enabled in the binaries, since it saves code space and might get in conflict with ```SERIAL```
