### ISSUE TITLE
IOS console

### ISSUE THREAD

**Issue by jmberger** [kscheff/BlueBasic#17]
Hi Kai,

Thank you for this very interresting project. I'm trying to move forward and successfully flashed the firmware on jdy-08. I made some research but could'nt find any working links to install the ios console app. Is there any ?

JM

**Comment by kscheff** [comment]
The iOS console is not available on the App Store. The Xcode project is here in this repo, so you can build and run it yourself. https://github.com/kscheff/BlueBasic/tree/master/Console/osx/BlueBasicConsole
