### ISSUE TITLE
PWM or pulse output ?

### ISSUE THREAD

**Issue by jmberger** [kscheff/BlueBasic#18]
Hi Kai,
Is there any feature or provision in the interpreter code regarding PWM or pulse output ? Something like this described here : https://e2e.ti.com/support/wireless-connectivity/bluetooth-group/bluetooth/f/bluetooth-forum/446812/cc2541-pwm-configuration

**Comment by kscheff** [comment]
I can't remember if such feature is built in. See interpreter source code and search for e.g. PWM.

**Comment by jmberger** [comment]
Will do and let you know.
