### ISSUE TITLE
Can't read from i2c sensors

### ISSUE THREAD

**Issue by 0xFACE** [kscheff/BlueBasic#7]
I'm trying to use I2C READ function to read from several i2c sensors (ie BMP180 barometric pressure sensor).
But no luck so far.   

The Wiki states following syntax for I2C reading:
`I2C READ <address>, <variable>[, ...]
`

As far as I know **address** value is the CHIP-ADDRESS.
But how to pass DATA-REGISTER-ADDRESS value ?

Do I have to use this sequence:
 `I2C WRITE 0XD0, 0X00, READ D`
taken from reading the DS3231 example.

Please explain.

**Comment by kscheff** [comment]
Yes, you have to use the the method to first write the chip address and sub register address before reading data. In this way BlueBasic issues a Restart. I don’t have actually tried this myself, it’s a good practice to use a scope to see how the bits are generated and if the BMP180 acknowledges the device address and data writes (sub address).

**Comment by kscheff** [comment]
Since there is no further feedback I close the issue here.
